config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  root 'invoices#index'

  post "add_collection" => "invoices#add_collection"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
	class Collection < ApplicationRecord
	  belongs_to :invoice
	  after_create do
	    self.invoice.update_pending_amount
	  end
	end

app/models/invoice.rb
	class Invoice < ApplicationRecord
		has_many :collections, dependent: :destroy	
		attr_accessor :from_page         
		attr_accessor :collection_amount

		def update_pending_amount		
			self.update(pending_amount: (self.amount - self.total_collection_amount))
		end	

		def total_collection_amount
			self.collections.try(:sum, :amount).try(:abs)
		end
		
	end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base	
end

app/controllers/invoices_controller.rb
    class InvoicesController < ApplicationController
      before_action :set_invoice, only: [:show, :edit, :update, :destroy]

      # GET /invoices
      # GET /invoices.json
      def index 
        @status = params[:status]
        invoices = Invoice.all
        if @status.blank?     
          @invoices_list = invoices
        elsif @status == "pending_bills"
          @invoices_list = invoices.where.not("pending_amount = ?", 0.0 || "0.0")    
        else @status == "collected_bills"
          @invoices_list = invoices.where("pending_amount = ?", 0.0 || "0.0")
        end  
      end

      # GET /invoices/1
      # GET /invoices/1.json
      def show
      end

      # GET /invoices/new
      def new
        @invoice = Invoice.new()
      end

      # GET /invoices/1/edit
      def edit
        @from_page = params[:from_page]
      end

      # POST /invoices
      # POST /invoices.json
      def create
        @invoice = Invoice.new(invoice_params)
        @invoice.pending_amount = @invoice.amount
        @invoice.invoice_date = Date.today

        respond_to do |format|
          if @invoice.save
            format.html { redirect_to invoices_path, notice: 'Invoice was successfully created.' }
            format.json { render :show, status: :created, location: @invoice }
          else
            format.html { render :new }
            format.json { render json: @invoice.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /invoices/1
      # PATCH/PUT /invoices/1.json
      def update
        Collection.create(invoice_id: @invoice.id, reference: @invoice.reference, amount: params[:invoice][:collection_amount], collection_date: Date.today)
        if params[:invoice][:from_page] == "show"
         redirect_to @invoice, notice: 'Collection is successfully added'
       else
        redirect_to invoices_path, notice: 'Collection is successfully added'
      end              
    end

      # DELETE /invoices/1
      # DELETE /invoices/1.json
      def destroy
        @invoice.destroy
        respond_to do |format|
          format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
      
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_invoice
          @invoice = Invoice.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def invoice_params
          params.require(:invoice).permit(:brand_manager, :narration, :invoice_date, :amount, :customer_name, :reference, :pending_amount, :collection_amount)
        end
      end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
        <div class="container">
          <div class="row"> 
            <%= form_with(model: invoice, local: true, id: "submit_collection") do |form| %>
            <% if invoice.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

              <ul>
                <% invoice.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <div class="form-group">        
             <h2><%= invoice.new_record? ? "New Bill" : "Add Collection"%></h2>     
           </div>
           <% if invoice.new_record? %> 
           <div class="form-group">        
            <%= form.label :reference, "Reference:" %>       
            <%= form.text_field :reference,class: "form-control", required: true %>       
          </div>


          <div class="form-group">        
            <%= form.label :brand_manager, "Brand Manager:" %>       
            <%= form.text_field :brand_manager,class: "form-control", required: true%>       
          </div>


          <!-- <div class="form-group">    
            <%#= form.label :invoice_date, "Invoice Date:"%><br>   
            <%#= form.date_select :invoice_date, class: "form-control", required: true %>    
          </div>
       -->

          <div class="form-group">
            <%= form.label :amount, "Amount:" %>    
            <%= form.text_field :amount, class: "form-control" , required: true, style: "" %> 
          </div>


          <div class="form-group">
            <%= form.label :narration, "Narration:" %>    
            <%= form.text_field :narration, class: "form-control", required:true %> 
          </div>


          <div class="form-group">
            <%= form.label :customer_name, "Customer Name:"%>   
            <%= form.text_field :customer_name, class: "form-control" %>
          </div>   

          <% else %>

          <div class="form-group">
            <div class="list-group">  
              <h5 class="list-group-item reference"><%= invoice.reference %></h5> 
              <h5 class="list-group-item"><%= @invoice.brand_manager %></h5>
            </div>       
          </div>
          <%= form.hidden_field :from_page, value: from_page%>
          <div class="form-group">       
            <%= form.text_field :collection_amount, class: "form-control collection_check", required: true, placeholder: "Enter the amount"%> 
          </div>

          <% end %>

          <footer>    
            <button type="submit" class="btn btn-primary btn-color btn-bg-color btn-xs col-xs-4 collection_button submit_collection">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Submit
            </button>
            <a type="button" class="btn btn-danger btn-color btn-bg-color btn-xs col-xs-4" href="<%=invoices_path%>">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Cancel
            </a>    
          </footer>  
          <% end %>  
        </div>
        </div>


      <script type="text/javascript">
          var amount = <%= raw @invoice.pending_amount %>
        $("#submit_collection").submit(function(e){

          if ($(".collection_check").length != 0 ){
          var col_original_value =  $(".collection_check").val();  
                var col_val = Math.round($(".collection_check").val());
                if ((isNaN(col_val) == false) && (isPositive(col_val) == true) && (col_original_value <= amount)){
                  $("#submit_collection").submit();      
                }else{
                  e. preventDefault();
                  alert("Pending amount is"+" "+amount+". Please enter the valid amount");
                }
          }else if($("#invoice_amount").length != 0){ 

            var amount_val = Math.round($("#invoice_amount").val());
                if ((isNaN(amount_val) == false) && (isPositive(amount_val) == true)){
                  $("#submit_collection").submit();      
                }else{
                  e. preventDefault();
                  alert("Please enter the valid amount");
                }
          }
        });

        function isPositive(n) {
              return /^[0-9]+$/.test(n);
          }
      </script>

app/views/invoices/edit.html.erb
<%= render 'form', invoice: @invoice, from_page: @from_page%>

app/views/invoices/index.html.erb
  <div class= "container">
    
    <% if @status == "pending_bills" %>
    <h2>PENDING BILLS</h2>
    <% elsif @status == "collected_bills" %>
    <h2>COLLECTED BILLS</h2>
    <%else %>
    <h2>INVOICE LIST</h2>
    <% end %>
    <br>

    <div class="btn-toolbar text-center well">
      <a type="button" class="btn btn-success btn-color btn-bg-color btn-sm col-xs-2 margin-left" href="<%= new_invoice_path%>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add a new bill
      </a>
      <a type="button" class="btn btn-success btn-color btn-bg-color btn-sm col-xs-2 margin-left" href="<%= invoices_path(status: 'pending_bills')%>">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Show Pending Bills
      </a>
      <a type="button" class="btn btn-success btn-color btn-bg-color btn-sm col-xs-2 margin-left" href="<%= invoices_path(status: 'collected_bills')%>">
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span> Show Collected Bills
      </a>
      <a type="button" class="btn btn-success btn-color btn-bg-color btn-sm col-xs-2 margin-left" href="<%= invoices_path()%>">
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span> Show all
      </a>     
    </div>


    <br>
    <div class="table-responsive">
      <table class= "table" id="customers">
        <thead>
          <tr>
            <th>Reference</th>
            <th>Invoice date</th>
            <th>Customer</th>
            <th>Brand manager</th>
            <th>Narration</th>
            <th>Amount</th>      
            <th>Total Collection</th>      
            <th>Balance Due</th>      
            <th>Button to add a collection</th>      
            <!-- <th colspan="3"></th> -->
          </tr>
        </thead>

        <tbody>
          <% @invoices_list.order(invoice_date: :desc).each do |invoice| %>     
          <tr>
            <td><%= link_to "#{invoice.reference}".html_safe, invoice %></td>
            <td><%= invoice.invoice_date %></td>
            <td><%= invoice.customer_name %></td>
            <td><%= invoice.brand_manager %></td>
            <td><%= invoice.narration %></td>       
            <td><%= invoice.amount %></td>        
            <td><%= invoice.try(:total_collection_amount)%></td>        
            <td><%= invoice.pending_amount %></td>        
            <td>
              <% if invoice.pending_amount > 0.0 %>
              <a type="button" class="btn btn-primary btn-sm col-xs-2 collection_button" href="<%=edit_invoice_path(id: invoice.id, from_page: "index")%>">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Collection
              </a>
              <% else %>
              <%= "Paid" %>
              <% end %>
            </td> 
          </tr>
          <% end %>
        </tbody>
      </table>
      <br>


      

app/views/invoices/new.html.erb
<%= render 'form', invoice: @invoice %>

app/views/invoices/show.html.erb
      
<div class="container">
  <div class="row">    
    <div class="form-group">        
     <h2>Invoice View</h2>     
   </div>
   <div class="list-group">  
    <h5 class="list-group-item reference"><%= link_to "#{@invoice.reference}".html_safe, invoices_path %></h5>
    <h5 class="list-group-item"><%= @invoice.customer_name %></h5>
    <h5 class="list-group-item"><%= @invoice.brand_manager %>
    </h5>
    <h5 class="list-group-item narration"><%= @invoice.narration %></h5>
  </div>

  <div class="table-responsive">
    <table class="table" id="customers">
      <thead>
        <tr>
          <th>Date</th>
          <th>Event</th>
          <th>Amount</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= @invoice.invoice_date %></td>
          <td><%= "New Invoice" %></td>
          <td><%= @invoice.try(:amount).blank? ? 0.0 : @invoice.try(:amount).try(:to_f) %></td> 
        </tr>
        <% collections = @invoice.try(:collections)%>

        <% unless collections.blank? %> 
        <% subt = @invoice.try(:amount) - collections.try(:sum, :amount) %>   
        <% collections.try(:each) do |collection| %>
        <tr>
          <td><%= collection.collection_date %></td>
          <td><%= "Collection" %></td>
          <td><%= "- #{collection.amount}" %></td>        
        </tr>
        <% end %>
        <% end %>
        <tr>
          <td></td>
          <td><%="Balance"%></td>
          <td><% if subt %>
            <%= subt.try(:to_f)%>
            <% else %>
            <%= @invoice.try(:amount).blank? ? 0.0 : @invoice.try(:amount).try(:to_f) %>
            <% end %>
          </td>        
        </tr>
      </tbody>
    </table>
  </div>
  <% if @invoice.pending_amount > 0.0 %>
  <footer>
    <a type="button" class="btn btn-primary btn-sm col-xs-2 collection_button" href="<%=edit_invoice_path(id: @invoice.id, from_page: "show")%>">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Collection
    </a>       
    <% end %>    
  </footer>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechnicalTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>